academy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('pagina/', include('pagina.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name="index"),
    path('servicos', views.service, name="servicos"),
    path('login', views.loginUser, name="login"),
    path('about_us', views.about_us, name="about-us"),
    path('pesquisar', views.pesquisar, name="pesquisar"),
    path('home', views.home, name="home"),
    path('registar_arquivos', views.registar_arquivos, name="registar-arquivos"),
    path('listar_arquivos', views.listar_arquivos, name="listar-arquivos"),
   
   
]

templates/app/about_us.html
<!--
@author [Gunza Ismael]
@email [7ilip@gmail.com]
@create date 2022-02-15 10:21:21
@modify date 2022-02-26 06:32:38
@desc [description]
-->

{% extends 'baseApp.html' %} {% block corpo %} {% load static %}
<section class="w3l-inner-page-main">
  <div class="breadcrumb-infhny-sobre-nos">
    <div class="container">
      <nav aria-label="breadcrumb">
        <h2 class="hny-title text-center"><span>Sobre Nós</span></h2>
      </nav>
    </div>
  </div>
</section>

<section class="w3l-contact-main">
  <div class="contact-infhny py-5">
    <div class="container py-lg-3">
      <div class="">
        <div class="cont-details">
          <div class="cont-top london text-center" data-aos="fade-up">
            <h6><span class="fa fa-map-marker"></span> QUEM SOMOS</h6>
            <p>
              O repositório integrado científico e académico teve a sua concepção em 2012, teve a sua execução plena em 2021 pela SOFIL WEB Empresa executora. O R.I.C.A- é a maior
              plataforma digital integrada Angolana do fórum académico e não só, proporcionando a comunidade académica uma vasta biblioteca virtual uma rede integrada de serviços
              digitais de investigação e ajuda académica
            </p>
            <!-- <p>
              O repositório integrado científico e académico teve a sua concepção em 2012 pelo seu fundador e CEO Engº WIK TANIMOR DOS SANTOS KAPACETE e teve a sua execução plena
              em 2021 em parceria com a SOFIL WEB Empresa executora. O R.I.C.A- é a maior plataforma digital integrada Angolana do fórum académico e não só, proporcionando a
              comunidade académica uma vasta biblioteca virtual uma rede integrada de serviços digitais de investigação e ajuda académica
            </p>-->
          </div>
          <div class="cont-top paris text-center" data-aos="fade-up">
            <h6><span class="fa fa-map-marker"></span> MISSÃO</h6>
            <p>A nossa missão é fazer chegar o conhecimento por meio do mundo digital a todos os cantos do globo.</p>
            <p><a href="#">+244 222 721 466 / + 244 916121016</a></p>
            <p><a href="#">Endereço: Av Murtala Mohamed, 35</a></p>
          </div>
          <div class="cont-top newyork text-center" data-aos="fade-up">
            <h6><span class="fa fa-map-marker"></span> VISÃO</h6>
            <p>
              Contribuir para o desenvolvimento da comunidade académica nacional e de forma global para o mundo. Elevar o poder de investigação a nível da sociedade académica
              agregando o poder do mundo digital Revolucionar as formas de aquisição do conhecimento e adoptar as novas tecnologias ao desenvolvimento da era digital
            </p>

            <p><a href="mailto:info@example.com"></a></p>
          </div>
        </div>

        <div class="map-content-9">
          <form action="#" method="post">
            <div class="form-top1">
              <h3 class="hny-title text-center mb-lg-5 mb-4" data-aos="fade-down">Enviar Sugestão</h3>
              <div class="form-top">
                <div class="form-top-left" data-aos="fade-up">
                  <input type="text" name="w3lName" id="w3lName" placeholder="Nome" required="" />

                  <input type="email" name="w3lSender" id="w3lSender" placeholder="Email*" required="" />

                  <input type="text" name="w3lSubject" id="w3lName" placeholder="Telefone" required="" />
                </div>
                <div class="form-top-righ" data-aos="fade-up">
                  <textarea name="w3lMessage" id="w3lMessage" placeholder="Sugestão*" required=""></textarea>
                </div>
              </div>
              <div class="text-center">
                <button type="submit">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/app/adicionar_arquivo.html
{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-9">
    <div class="card" style="min-height: 484px">
      
          <div class="card-header">
            <h3>Adicionar Novo Arquivo</h3>
          </div>
          <div class="card-body">
            <form class="forms-sample" action="{% url 'app:registar-arquivos' %}" method="POST" enctype="multipart/form-data">
             {% csrf_token %} {% autoescape on %}
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Titulo<span class="text-danger">*</span></label>
                    {{ form.titulo }}{{ form.titulo.errors }}
                    
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group ">
                    <label for="" class="">Autor</label>
                    {{ form.autor }}{{ form.autor.errors }}
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Número de Pagina<span class="text-danger">*</span></label>
                    {{ form.numero_pagina }}{{ form.numero_pagina.errors }}
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group ">
                    <label for="" class="">Categoria<span class="text-danger">*</span></label>
                    {{ form.tipologia }}{{ form.tipologia.errors }}
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group">
                    <label for="" class="">Data de Criação</label>
                    {{ form.data }}{{ form.data.errors }}
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="form-group ">
                    <label for="" class="">Descrição</label>
                    {{ form.descricao }}{{ form.descricao.errors }}
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group">
                    <label for="" class="">Arquivo</label>
                    {{ form.arquivo }}{{ form.arquivo.errors }}
                  
                  </div>
                </div>

              </div>

              <div class="form-group">
                <div id="visitfromworld" style="width: 100%; height: 20px"></div>
              </div>
              <button type="submit" class="btn btn-primary mr-2" style="width: 40%; height: 38px">SALVAR</button>
              {% endautoescape %}
            </form>
          </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

templates/app/home.html
{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="row">
  <div class="col-xl-3 col-md-6">
    <div class="card prod-p-card card-red">
      <div class="card-body">
        <div class="row align-items-center mb-30">
          <div class="col">
            <h6 class="mb-5 text-white">Dissertação e Monografias</h6>
            <h3 class="mb-0 fw-700 text-white">1,783</h3>
          </div>
          <div class="col-auto">
            <i class="fa fa-users text-red f-18"></i>
          </div>
        </div>
        <p class="mb-0 text-white"><span class="label label-danger mr-10">+11%</span></p>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6">
    <div class="card prod-p-card card-blue">
      <div class="card-body">
        <div class="row align-items-center mb-30">
          <div class="col">
            <h6 class="mb-5 text-white">Artigos Ciéntifico</h6>
            <h3 class="mb-0 fw-700 text-white">15,830</h3>
          </div>
          <div class="col-auto">
            <i class="fas fa-database text-blue f-18"></i>
          </div>
        </div>
        <p class="mb-0 text-white"><span class="label label-primary mr-10">+12%</span></p>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6">
    <div class="card prod-p-card card-green">
      <div class="card-body">
        <div class="row align-items-center mb-30">
          <div class="col">
            <h6 class="mb-5 text-white">Teses</h6>
            <h3 class="mb-0 fw-700 text-white">6,780</h3>
          </div>
          <div class="col-auto">
            <i class="fas fa-dollar-sign text-green f-18"></i>
          </div>
        </div>
        <p class="mb-0 text-white"><span class="label label-success mr-10">+52%</span></p>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-md-6">
    <div class="card prod-p-card card-yellow">
      <div class="card-body">
        <div class="row align-items-center mb-30">
          <div class="col">
            <h6 class="mb-5 text-white">Arquivos</h6>
            <h3 class="mb-0 fw-700 text-white">6,784</h3>
          </div>
          <div class="col-auto">
            <i class="fas fa-tags text-warning f-18"></i>
          </div>
        </div>
        <p class="mb-0 text-white"><span class="label label-warning mr-10">+52%</span></p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="card"></div>
  </div>
  <div class="col-md-4">
    <div class="">
      <div class="text-center">
        <div class="profile-pic mt-20">
          <!-- <img src="{% static '/img/user.jpg' %}" width="260" class="rounded-circle" alt="user" />-->
          <h4 class="mt-20 mb-0"></h4>
          <a href="#"></a>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="card"></div>
  </div>
</div>

{% endblock %}

templates/app/index.html
<!--
Author: SOFIL WEB
Author URL: 
-->

{% extends 'baseApp.html' %} {% block corpo %} {% load static %}
<!--//top-header-content-->
<!--w3l-banner-slider-->
<section class="w3l-banner-main">
  <!--/banner-content-->
  <div class="bannerhny-content text-center">
    <h3 data-aos="fade-up">REPOSITÓRIO INTEGRADO CIENTÍFICO & <br /><span>ACADÉMICO DE ANGOLA</span></h3>

    <h6 data-aos="fade-up">
      Aproveite o infinito mundo da pesquisa e ajuda académica com mais de 30.000 livros e trabalhos já feitos e <br />
      divulgados pelas instituições reconhecidas pelo Ministério do Ensino Superior e Tecnologia de Inovação.
    </h6>
    <div class="banner-button" data-aos="fade-down">
      <a href="{% url 'app:pesquisar' %}" class="btn">PESQUISAR</a>
    </div>
  </div>
  <!--//banner-content-->
</section>

<section class="w3l-content-12-main">
  <!-- /content-6-section -->
  <div class="content-12 text-left py-5">
    <div class="container pt-lg-3">
      <h3 class="hny-title text-center">Os nossos Serviços</h3>
      <div class="content-info-tabs mt-4">
        <div class="tab-main mx-auto text-md-center">
          <input id="tab1" type="radio" name="tabs" checked />
          <label for="tab1"><span class="fa fa-book" aria-hidden="true"></span> Tese de Doutoramento</label>

          <input id="tab2" type="radio" name="tabs" />
          <label for="tab2"><span class="fa fa-credit-card" aria-hidden="true"></span> Dissertação e Monografias </label>

          <input id="tab3" type="radio" name="tabs" />
          <label for="tab3"><span class="fa fa-search" aria-hidden="true"></span> Artigos Ciéntifico</label>
          <input id="tab4" type="radio" name="tabs" />
          <label for="tab4"><span class="fa fa-trophy" aria-hidden="true"></span> Relatórios</label>
          <section id="content1" data-aos="zoom-in">
            <div class="content-info-in row mt-lg-5 mt-4">
              <div class="content-gd col-md-5" data-aos="zoom-in">
                <img src="{% static '/asset/images/screen-1.png' %}" class="img-fluid" alt="" />
              </div>
              <div class="content-gd col-md-5 mt-4">
                <p>Os trabalhos de Tese de Doutoramento são publicados pelas instituições do ensio supeior reconhecidas pelo estados, e pelos nucelos associados as instuitções.</p>
              </div>
            </div>
          </section>

          <section id="content2" data-aos="zoom-in">
            <div class="content-info-in row mt-lg-5 mt-4">
              <div class="content-gd col-md-5" data-aos="zoom-in">
                <img src="{% static '/asset/images/screen-2.png' %}" class="img-fluid" alt="" />
              </div>
              <div class="content-gd col-md-5 mt-4">
                <p>A Dissertação e Monografias são publicados pelas instituições e membros pertecente ao trabalho, com referida aprovação do mesmo.</p>
              </div>
            </div>
          </section>

          <section id="content3" data-aos="zoom-in">
            <div class="content-info-in row mt-lg-5 mt-4">
              <div class="content-gd col-md-5" data-aos="zoom-in">
                <img src="{% static '/asset/images/5.png' %}" class="img-fluid" alt="" />
              </div>
              <div class="content-gd col-md-5 mt-4">
                <p>Os Artigos Ciéntifico, são publicados pelas instituições e membros reconhecidos pelo nucleo académico angolano, com referida justificação.</p>
              </div>
            </div>
          </section>

          <section id="content4" data-aos="zoom-in">
            <img src="{% static '/asset/images/screen-4.png' %}" class="img-fluid" alt="mobile-image" />
          </section>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- //content-6-section -->
<section class="w3l-content-6">
  <!-- /content-6-section -->
  <div class="content-6-mian py-5">
    <div class="container py-lg-3">
      <h3 class="hny-title text-center">REPOSITÓRIO</h3>
      <div class="content-info-in row mt-lg-5 mt-4">
        <div class="content-gd col-md-5 text-lg-right">
          Ajudamos você a terminar o seu trabalho académico com sucesso. Temos para si uma vasta lista de temas de Tese de Doutoramento, Dissertação, Monografias, Relatórios.
          <br />
          Contacte-nos já e não perca mais tempo!
        </div>
        <div class="content-gd col-md-4" data-aos="zoom-in">
          <img src="{% static '/asset/images/1.png' %}" class="img-fluid" alt="" />
        </div>
      </div>
    </div>
  </div>
</section>
<!-- //content-6-section -->

<section class="w3l-content-w-photo-6">
  <!-- /content-grids-->
  <div class="content-photo-info py-5">
    <div class="container py-lg-3">
      <h3 class="hny-title text-center">
        <!--Features-->
      </h3>
      <!-- /row-->
      <div class="content-photo-grids row mt-lg-5 mt-4 px-lg-5">
        <div class="photo-6-inf-left col-lg-6 pr-lg-4" data-aos="fade-up">
          <img src="{% static '/asset/images/2.png' %}" class="img-fluid" alt="" />
        </div>
        <div class="photo-6-inf-right col-lg-6 text-left pl-lg-5" data-aos="fade-down">
          <h4>Divulgação!</h4>
          <p>
            Divulgamos todos os conteúdos com cariz académico, investigativo, científico e outros de forma a contribuir para o desenvolvimento do conhecimento e das instituições
            parceiros
          </p>
        </div>
      </div>
      <!-- //row-->
      <!-- /row-->
      <div class="content-photo-grids row py-lg-5 py-4 mt-lg-5 mt-4 px-lg-5">
        <div class="photo-6-inf-right col-lg-6 text-left pr-lg-5" data-aos="fade-down">
          <h4>Depósito</h4>
          <p>
            O serviço de depósito permite aos utilizadores e pesquisadores garantirem a continuidade dos seus trabalhos e serem fontes de pesquisas futuras, quer particulares ou
            institucionais.
          </p>
        </div>
        <div class="photo-6-inf-left col-lg-6 pr-lg-4" data-aos="fade-up">
          <img src="{% static '/asset/images/3.png' %}" class="img-fluid" alt="" />
        </div>
      </div>
      <!-- //row-->
    </div>
  </div>
</section>
<!-- /macbook--->
<section class="w3l-macbook-content-6">
  <div class="macbook-infohny">
    <!-- /macbook-infohny-->
    <div class="container-fuild">
      <div class="row macbook-infohny-inn mx-lg-0">
        <div class="col-lg-6 macbook-left mt-lg-0 mt-5 px-lg-0" data-aos="fade-up">
          <img src="{% static '/asset/images/macbook-1.png' %}" class="img-fluid" alt="" />
        </div>
        <div class="col-lg-6 macbook-right my-lg-5 py-lg-5 py-4" data-aos="fade-down">
          <h3 class="hny-title mb-lg-5">TEMAS PESQUISADOS.</h3>
          <div class="row macbook-right-grids mb-lg-3 mb-3">
            <div class="col-md-10 macbook-right-info">
              <h6><a href="#">Direito Constitucional</a></h6>
            </div>
          </div>
          <div class="row macbook-right-grids mb-3 mt-lg-0 mt-3">
            <div class="col-md-10 macbook-right-info">
              <h6><a href="#">Autarquias Locais</a></h6>
            </div>
          </div>
          <div class="row macbook-right-grids mb-3 mb-lg-3 mb-3">
            <div class="col-md-10 macbook-right-info">
              <h6><a href="#">Administração e Empresas</a></h6>
            </div>
          </div>
          <div class="row macbook-right-grids mb-3 mb-lg-3 mb-3">
            <div class="col-md-10 macbook-right-info">
              <h6><a href="#">Segurança de Informação</a></h6>
            </div>
          </div>
          <div class="row macbook-right-grids mb-lg-0 mb-4">
            <div class="col-md-10 macbook-right-info">
              <h6><a href="#">Gestão de recursos Humanos</a></h6>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- //macbook-infohny-->
  </div>
</section>
<!-- //macbook--->
<section class="w3l-content-5">
  <!-- /content-6-section -->
  <div class="content-5-main">
    <div class="container">
      <div class="content-info-in pt-5">
        <div class="content-gd pt-lg-5">
          <h3 class="hny-title" data-aos="fade-up">
            Os Nossos Parcerios
            <br />Instituições
          </h3>

          <img src="{% static '/asset/images/macbook-2.png' %}" class="img-fluid" alt="" />
        </div>
      </div>
    </div>
  </div>
</section>
<!-- //content-6-section -->
<!--/w3l-download-main-->

<!--//w3l-download-main-->

{% endblock %}

templates/app/listar_arquivos.html
{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<div class="card">
  <div class="card-header row"><h3>Lista de Arquivos Disponivel</h3></div>
  <div class="card-body">
    <table id="advanced_table" class="table">
      <thead>
        <tr>
          <th>Autor</th>
          <th>Titulo</th>
          <th>Tipologia</th>
          <th>Nº de Paginas</th>
          <th>Data</th>
          <th class="no-link last"><span class="nobr">Opções</span></th>
        </tr>
      </thead>
      <tbody>
        {% for dados in lista %}
        <tr>
          <td class="">{{ dados.autor|upper }}</td>
          <td class="">{{ dados.titulo|upper|truncatechars:40 }}</td>
          <td class="">{{ dados.tipologia|upper }}</td>
          <td class="">{{ dados.numero_pagina }}</td>
          <td class="">{{ dados.data|upper }}</td>
          <td>
            <ul class="nav nav-pills">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                  >Acção <i class="ik ik-chevron-down"></i
                ></a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">VISUALIZAR</a>

                  <div class="dropdown-divider"></div>
                </div>
              </li>
            </ul>
          </td>
          <td></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/app/login.html
{% extends 'baseApp.html' %} {% block corpo %} {% load static %}
<section class="w3l-contact-main">
  <div class="contact-infhny py-5">
    <div class="container py-lg-3">
      <div class="map-content-9">
        <form action="{% url 'app:home' %}" method="POST">
          {% csrf_token %}
          <div class="form-top1">
            <h3 class="hny-title text-center mb-lg-5 mb-4" data-aos="fade-down">Login User</h3>

            <div class="row">
              <div class="col-md-3"></div>
              <div class="form-top col-md-6">
                <div class="" data-aos="fade-up">
                  <input type="email" name="w3lSender" id="w3lSender" placeholder="Email*" required="" />
                </div>
                <div class="" data-aos="fade-up">
                  <input type="password" name="w3lName" id="w3lName" placeholder="Password" required="" />
                </div>
              </div>
            </div>
            <div class="text-center">
              <button type="submit">Submit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  {% endblock %}
</section>

templates/app/pesquisar.html
{% extends 'baseApp.html' %} {% block corpo %} {% load static %}
<section class="w3l-contact-main">
  <div class="contact-infhny py-5">
    <div class="container py-lg-3">
      <div class="map-content-9">
        <form action="{% url 'app:pesquisar' %}" method="POST">
          {% csrf_token %}
          <div class="form-top1">
            <h5 class="hny-title text-center mb-lg-5 mb-4" data-aos="fade-down">Pesquisar Arquivos</h5>

            <div class="row">
              <div class="col-md-3"></div>
              <div class="form-top col-md-6">
                <div class="" data-aos="fade-up">{{ form.titulo }}{{ form.titulo.errors }}</div>
                <div class="" data-aos="fade-up"></div>
              </div>
            </div>

            <div class="text-center">
              <button type="submit">Enviar</button>
            </div>
          </div>
        </form>
      </div>
      {% if lista is not null %}
      <div class="row">
        <div class="col-md-12"></div>
        <div class="card">
          <div class="card-header row"><h3>Resultados</h3></div>
          <div class="card-body">
            <table id="advanced_table" class="table">
              <thead>
                <tr>
                  <th>Autor</th>
                  <th>Titulo</th>
                  <th>Tipologia</th>
                  <th>Nº de Paginas</th>
                  <th>Data</th>
                  <th class="no-link last"><span class="nobr">Opções</span></th>
                </tr>
              </thead>
              <tbody>
                {% for dados in lista %}
                <tr>
                  <td class="">{{ dados.autor|upper }}</td>
                  <td class="">{{ dados.titulo|upper|truncatechars:40 }}</td>
                  <td class="">{{ dados.tipologia|upper }}</td>
                  <td class="">{{ dados.numero_pagina }}</td>
                  <td class="">{{ dados.data|upper }}</td>
                  <td>
                    <ul class="nav nav-pills">
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"
                          >Acção <i class="ik ik-chevron-down"></i
                        ></a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="#">VISUALIZAR</a>

                          <div class="dropdown-divider"></div>
                        </div>
                      </li>
                    </ul>
                  </td>
                  <td></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}

templates/app/service.html
<!--
@author [sofil web]
@email [7ilip@gmail.com]
@create date 2022-02-14 09:46:11
@modify date 2022-02-14 10:13:58
@desc [description]
-->

<!--//top-header-content-->

{% extends 'baseApp.html' %}{% block corpo %}{% load static %}
    <section class="w3l-inner-page-main">
      <div class="breadcrumb-infhny">
        <div class="container">
          <nav aria-label="breadcrumb">
            <h2 class="hny-title text-center">Serviços</h2>
            
          </nav>
        </div>
      </div>
    </section>
<section class="features-4">
	<div class="features4-block py-5">
		<div class="container py-lg-5">
			<h3 class="hny-title text-center" data-aos="fade-down">Categorias Académicas</h3>
			
			<div class="features4-grids text-left row mt-5">
				<div class="col-lg-4 col-md-6 features4-grid" data-aos="fade-up">
					<div class="features4-grid-inn">
						<span class="fa fa-pencil-square-o icon-fea4" aria-hidden="true"></span>
						<h5><a href="#URL">Ciências Biológicas e Saúde</a></h5>
						<p></p>

					</div>
				</div>
				<div class="col-lg-4 col-md-6 features4-grid" data-aos="fade-up">
						<div class="features4-grid-inn">
							<span class="fa fa-umbrella icon-fea4" aria-hidden="true"></span>
							<h5><a href="#URL">Arquitectura, Construção Civil</a></h5>
							<p></p>
	
						</div>
					</div>
					<div class="col-lg-4 col-md-6 features4-grid third" data-aos="fade-up">
							<div class="features4-grid-inn">
								<span class="fa fa-cogs icon-fea4" aria-hidden="true"></span>
								<h5><a href="#URL">Engenharia e Tecnologia</a></h5>
								<p></p>
		
							</div>
						</div>
						<div class="col-lg-4 col-md-6 features4-grid" data-aos="fade-up">
							<div class="features4-grid-inn">
								<span class="fa fa-spinner icon-fea4" aria-hidden="true"></span>
								<h5><a href="#URL">Matemática, Física, Química</a></h5>
								<p></p>
		
							</div>
						</div>
						<div class="col-lg-4 col-md-6 features4-grid" data-aos="fade-up">
								<div class="features4-grid-inn">
									<span class="fa fa-shield icon-fea4" aria-hidden="true"></span>
									<h5><a href="#URL">Gestão, Administração e Empresas</a></h5>
									<p></p>
			
								</div>
							</div>
							<div class="col-lg-4 col-md-6 features4-grid third" data-aos="fade-up">
									<div class="features4-grid-inn">
										<span class="fa fa-book icon-fea4" aria-hidden="true"></span>
										<h5><a href="#URL">Língua, Comunicação e Cultura</a></h5>
										<p></p>
				
									</div>
								</div>
							</div>
			</div>
		</div>
	</div>
</section>
<!-- features-4 -->
<section class="w3l-services-6-main">
	<div class="services-6 py-5">
		<div class="container py-md-3">
			<div class="row serv_sec_info">
				<div class="col-md-6 banner_bottom_grid help" data-aos="fade-down">
					<img src="{% static '/asset/images/macbook-2.png' %}" alt=" " class="img-fluid">
				</div>
				<div class="col-md-6 banner_bottom_left pl-lg-4" data-aos="fade-up">
					<h4><a class="link-hny" href="#">
							Os melhores artigos e
                            obras científicas do mês!</a></h4>
					<p>Pellentesque convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla
						viverra pharetra sem, eget
						pulvinar neque pharetra ac.Lorem ipsum dolor sit amet,Ea consequuntur illum facere aperiam sequi optio consectetur.</p>
					<p>Lorem Ipsum convallis diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla viverra
						pharetra sem, eget
						pulvinar neque pharetra ac.</p>
					<a class="read-more-btn btn mt-3" href="#">Informação</a>

				</div>
			</div>
			
		</div>
	</div>
</section>
 
{% endblock %}
   