academy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('pagina/', include('pagina.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name="index"),
    path('servicos', views.service, name="servicos"),
    path('login', views.loginUser, name="login"),
    path('about_us', views.about_us, name="about-us"),
    path('pesquisar', views.pesquisar, name="pesquisar"),
    path('home', views.home, name="home"),
    path('registar_arquivos', views.registar_arquivos, name="registar-arquivos"),
    path('listar_arquivos', views.listar_arquivos, name="listar-arquivos"),
   
   
]

pagina/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'pagina'
urlpatterns = [
    path('index/', views.index, name="index"),
    path('registar/', views.registar, name="registar-se"),
    path('loginUser/', views.loginUser, name="loginUser"),
    path('service', views.service, name="service"),
    path('parceiros/', views.parceiros, name="parceiros"),
    path('about/', views.about_us, name="about_us"),
    path('resultado_pesquisa', views.resultado_pesquisa, name="resultado_pesquisa"),
    path('visualizar/<int:pk>/', views.visualizar, name="visualizar"),
]

pagina/models.py
from django.db import models
from core.opcoes import CATEGORIA, TIPO
# Create your models here.

class Documenmto(models.Model):
    titulo = models.CharField(max_length=520)
    instituicao = models.CharField(max_length=220, blank=True, null=True,default="")
    ano = models.CharField(max_length=4)
    autor = models.CharField(max_length=400)
    resumo = models.TextField(max_length=500, blank=True, null=True, default="")
    palavras_chaves = models.CharField(max_length=350, blank=True, null=True, default="")
    categoria = models.CharField(max_length=120, choices=CATEGORIA)
    tipo = models.CharField(max_length=100, choices=TIPO)
    editora = models.CharField(max_length=300, blank=True, null=True, default="")
    orientador = models.CharField(max_length=400, blank=True, null=True, default="")
    uri = models.URLField(max_length=300, blank=True, null=True, default="")
    tipo_acesso = models.CharField(max_length=200, blank=True, null=True, default="")
    data_publicacao = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    arquivo = models.FileField(upload_to='uploads/%Y/', blank=True, null=True)

    def __str__ (self):
        return "%d" % (self.id)

pagina/forms.py
from django import forms
from django.forms import ModelForm
from core.opcoes import CATEGORIA, TIPO

class Pesquisa_Forms(forms.Form):
    #categoria = forms.CharField(widget=forms.Select(choices=CATEGORIA, attrs={'class': 'form-control', 'id':'choices-to'}))
    #tipo = forms.CharField(widget=forms.Select(choices=TIPO, attrs={'class': 'form-control', 'id':'choices-to'}))
    titulo = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control maiuscula'}))

pagina/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from pagina.models import Documenmto
from pagina.forms import Pesquisa_Forms
from django.db.models import Count, Exists, Q
from app.models import Arquivo

# Create your views here.

def index(request):
    form = Pesquisa_Forms(request.POST or None)
   
    context = {'form': form}
    return render(request, 'pagina/index.html', context)



def resultado_pesquisa(request):
    form = Pesquisa_Forms(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            #categoria = form.cleaned_data.get('categoria')
            #tipo = form.cleaned_data.get('tipo')
            titulo = form.cleaned_data.get('titulo')
            #resp = Profissao.objects.select_related('estudante').filter(Q(estudante__pessoa__bi__contains=bi) | Q(estudante__pessoa__passaporte=bi) | Q(estudante__numero_estudante__contains=bi) )
            lista = Arquivo.objects.select_related().filter(Q(titulo__contains=titulo)).all()
            context = {'form': form,'lista': lista}
            return render(request, 'pagina/resultado_pesquisa.html', context)
    context = {'form': form}
    return render(request, 'pagina/resultado_pesquisa.html', context)


def about_us(request):
    context = {}
    return render(request, 'pagina/about.html', context)


def registar(request):
    context = {}
    return render(request, 'pagina/registar.html', context)


def loginUser(request):
    context = {}
    return render(request, 'pagina/sign.html', context)


def service(request):
    form = Pesquisa_Forms(request.POST or None)
   
    context = {'form': form}
    return render(request, 'pagina/service.html', context)


def parceiros(request):
    form = Pesquisa_Forms(request.POST or None)
   
    context = {'form': form}
    return render(request, 'pagina/parceiros.html', context)


def visualizar(request, pk):
    resp = Documenmto.objects.get(id=pk)
   
    context = {'resp': resp}
    return render(request, 'pagina/visualizar.html', context)

templates/pagina/about.html
{% extends 'base_pagina.html' %}{% block corpo %}{% load static %}
<header>
  <div class="page-header min-height-400" style="background-image: url('../static/assets/img/city-profile.jpg')" loading="lazy">
    <span class="mask bg-gradient-dark opacity-8"></span>
  </div>
</header>
<!-- -------- END HEADER 4 w/ search book a ticket form ------- -->
<div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
  <!-- START Testimonials w/ user image & text & info -->
  <section class="py-sm-7 py-5 position-relative">
    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
          <!--
            <div class="mt-n8 mt-md-n9 text-center">
            <img class="avatar avatar-xxl shadow-xl position-relative z-index-2" src="../assets/img/bruce-mars.jpg" alt="bruce" loading="lazy" />
          </div>
          -->

          <div class="row py-3">
            <div class="col-lg-10 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mx-auto">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h3 class="mb-0 btn bg-gradient-info">QUEM SOMOS</h3>
                <div class="d-block">
                  <button type="button" class="btn btn-sm btn-outline-info text-nowrap mb-0">Follow</button>
                </div>
              </div>
              <p class="text-lg mb-0">
                O repositório integrado científico e académico teve a sua concepção em 2012 pelo seu fundador e CEO Engº WIK TANIMOR DOS SANTOS KAPACETE e teve a sua execução plena em 2021 em parceria com a SOFIL WEB Empresa executora.
              </br>
                O R.I.C.A- é a maior plataforma digital integrada Angolana do fórum académico e não só, proporcionando a comunidade académica uma 
                vasta biblioteca virtual uma rede integrada de serviços digitais de investigação e ajuda académica <br />
                <!--
                  O repositório integrado científico e académico teve a sua concepção em 2012 pelo seu fundador e CEO Engº Wik Tanimor Dos Santos Kaoacete e teve a sua execução plena em 2021 em parceria com a SOFIL WEB Empresa executora.
                -->
                <a
                  href="javascript:;"
                  class="text-info icon-move-right"
                >
                </a>
              </p>
            </div>

            <div class="col-lg-10 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mx-auto py-3">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h3 class="mb-0 btn bg-gradient-danger">MISSÃO</h3>
                <div class="d-block">
                  <button type="button" class="btn btn-sm btn-outline-info text-nowrap mb-0">Follow</button>
                </div>
              </div>
              <p class="text-lg mb-0">
                A nossa missão é fazer chegar o conhecimento por meio do mundo digital a todos os cantos do globo.
                <br /><a href="javascript:;" class="text-info icon-move-right"> </a>
              </p>
            </div>

            <div class="col-lg-10 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mx-auto py-3">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h3 class="mb-0 btn bg-gradient-warning">VISÃO</h3>
                <div class="d-block">
                  <button type="button" class="btn btn-sm btn-outline-info text-nowrap mb-0">Follow</button>
                </div>
              </div>
              <p class="text-lg mb-0">
                Contribuir para o desenvolvimento da comunidade académica nacional e de forma global para o mundo. 
                 </br>
                Elevar o poder de investigação a nível da sociedade académica agregando o poder do mundo digital
                </br>
                Revolucionar as formas de aquisição do conhecimento e adoptar as novas tecnologias ao desenvolvimento da era digital
                <a href="javascript:;" class="text-info icon-move-right"> </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- END Testimonials w/ user image & text & info -->
  <!-- START Blogs w/ 4 cards w/ image & text & link -->

  <!--
  <section class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <h3 class="mb-5">Check my latest blogposts</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3 col-sm-6">
          <div class="card card-plain">
            <div class="card-header p-0 position-relative">
              <a class="d-block blur-shadow-image">
                <img src="../assets/img/examples/testimonial-6-2.jpg" alt="img-blur-shadow" class="img-fluid shadow border-radius-lg" loading="lazy" />
              </a>
            </div>
            <div class="card-body px-0">
              <h5>
                <a href="javascript:;" class="text-dark font-weight-bold">Rover raised $65 million</a>
              </h5>
              <p>Finding temporary housing for your dog should be as easy as renting an Airbnb. That’s the idea behind Rover ...</p>
              <a href="javascript:;" class="text-info text-sm icon-move-right"
                >Read More
                <i class="fas fa-arrow-right text-xs ms-1"></i>
              </a>
            </div>
          </div>
        </div>

        <div class="col-lg-3 col-md-12 col-12">
          <div class="card card-blog card-background cursor-pointer">
            <div class="full-background" style="background-image: url('../assets/img/examples/blog2.jpg')" loading="lazy"></div>
            <div class="card-body">
              <div class="content-left text-start my-auto py-4">
                <h2 class="card-title text-white">Flexible work hours</h2>
                <p class="card-description text-white">Rather than worrying about switching offices every couple years, you stay in the same place.</p>
                <a href="javascript:;" class="text-white text-sm icon-move-right"
                  >Read More
                  <i class="fas fa-arrow-right text-xs ms-1"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
--></div>
<section class="py-lg-5">
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="card box-shadow-xl overflow-hidden mb-5">
          <div class="row">
            <div class="col-lg-5 position-relative bg-cover px-0" style="background-image: url('../static/assets/img/examples/blog2.jpg')" loading="lazy">
              <div class="z-index-2 text-center d-flex h-100 w-100 d-flex m-auto justify-content-center">
                <div class="mask bg-gradient-dark opacity-8"></div>
                <div class="p-5 ps-sm-8 position-relative text-start my-auto z-index-2">
                  <h3 class="text-white">Informação de Contacto</h3>
                  <p class="text-white opacity-8 mb-4"></p>
                  <div class="d-flex p-2 text-white">
                    <div>
                      <i class="fas fa-phone text-sm"></i>
                    </div>
                    <div class="ps-3">
                      <span class="text-sm opacity-8">+244 222 721 466 / + 244 916121016</span>
                    </div>
                  </div>
                  <div class="d-flex p-2 text-white">
                    <div>
                      <i class="fas fa-envelope text-sm"></i>
                    </div>
                    <div class="ps-3">
                      <span class="text-sm opacity-8">hello@creative-tim.com</span>
                    </div>
                  </div>
                  <div class="d-flex p-2 text-white">
                    <div>
                      <i class="fas fa-map-marker-alt text-sm"></i>
                    </div>
                    <div class="ps-3">
                      <span class="text-sm opacity-8">Endereço: Av Murtala  Mohamed, 35</span>
                    </div>
                  </div>
                  <div class="mt-4">
                    <button
                      type="button"
                      class="btn btn-icon-only btn-link text-white btn-lg mb-0"
                      data-toggle="tooltip"
                      data-placement="bottom"
                      data-original-title="Log in with Facebook"
                    >
                      <i class="fab fa-facebook"></i>
                    </button>
                    <button
                      type="button"
                      class="btn btn-icon-only btn-link text-white btn-lg mb-0"
                      data-toggle="tooltip"
                      data-placement="bottom"
                      data-original-title="Log in with Twitter"
                    >
                      <i class="fab fa-twitter"></i>
                    </button>
                    <button
                      type="button"
                      class="btn btn-icon-only btn-link text-white btn-lg mb-0"
                      data-toggle="tooltip"
                      data-placement="bottom"
                      data-original-title="Log in with Dribbble"
                    >
                      <i class="fab fa-dribbble"></i>
                    </button>
                    <button
                      type="button"
                      class="btn btn-icon-only btn-link text-white btn-lg mb-0"
                      data-toggle="tooltip"
                      data-placement="bottom"
                      data-original-title="Log in with Instagram"
                    >
                      <i class="fab fa-instagram"></i>
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-7">
              <form class="p-3" id="contact-form" method="post">
                <div class="card-header px-4 py-sm-5 py-3">
                  <h2>Enviar Sugestão</h2>
                  <p class="lead"></p>
                </div>
                <div class="card-body pt-1">
                  <div class="row">
                    <div class="col-md-6 pe-2 mb-3">
                      <div class="input-group input-group-static mb-4">
                        <label>Nome</label>
                        <input type="text" class="form-control" placeholder="" />
                      </div>
                    </div>

                    <div class="col-md-6 pe-2 mb-3">
                      <div class="input-group input-group-static mb-4">
                        <label>Telefone</label>
                        <input type="text" class="form-control" placeholder="" />
                      </div>
                    </div>
                    <div class="col-md-6 pe-2 mb-3">
                      <div class="input-group input-group-static mb-4">
                        <label>E-mail</label>
                        <input type="email" class="form-control" placeholder="" />
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-6 text-end ms-auto">
                      <button type="submit" class="btn bg-gradient-info mb-0">ENVIAR</button>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/pagina/forms.html
<section>
  <div class="container py-4">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
        <h3 class="text-center">Contact us</h3>
        <form role="form" id="contact-form" method="post" autocomplete="off">
          <div class="card-body">
            <div class="row">
              <div class="col-md-6">
                <div class="input-group input-group-dynamic mb-4">
                  <label class="form-label">First Name</label>
                  <input class="form-control" aria-label="First Name..." type="text" />
                </div>
              </div>
              <div class="col-md-6 ps-2">
                <div class="input-group input-group-dynamic">
                  <label class="form-label">Last Name</label>
                  <input type="text" class="form-control" placeholder="" aria-label="Last Name..." />
                </div>
              </div>
            </div>
            <div class="mb-4">
              <div class="input-group input-group-dynamic">
                <label class="form-label">Email Address</label>
                <input type="email" class="form-control" />
              </div>
            </div>
            <div class="input-group mb-4 input-group-static">
              <label>Your message</label>
              <textarea name="message" class="form-control" id="message" rows="4"></textarea>
            </div>
            <div class="row">
              <div class="col-md-12">
                <div class="form-check form-switch mb-4 d-flex align-items-center">
                  <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" checked="" />
                  <label class="form-check-label ms-3 mb-0" for="flexSwitchCheckDefault"
                    >I agree to the <a href="javascript:;" class="text-dark"><u>Terms and Conditions</u></a
                    >.</label
                  >
                </div>
              </div>
              <div class="col-md-12">
                <button type="submit" class="btn bg-gradient-dark w-100">Send Message</button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

templates/pagina/parceiros.html
{% extends 'base_pagina.html' %}{% block corpo %}{% load static %}
<header>
  <div class="page-header min-height-400" style="background-image: url('../static/assets/img/banners/parceiro.jpg')" loading="lazy">
    <span class="mask bg-gradient-dark opacity-8"></span>
  </div>
</header>
<section class="py-5 bg-gray-100">
  <div class="container">
    <div class="row">
      <div class="col-md-7 mx-auto text-center mb-5">
        <h3>Os Nossos Parceiros</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-4 col-sm-4">
        <div class="mt-md-0 mt-5">
          <div class="card-header mt-n4 mx-3 p-0 bg-transparent position-relative z-index-2">
            <a class="d-block blur-shadow-image">
              <img src="{% static '/assets/img/parceiros/estado.jpeg' %}" alt="img-blur-shadow" class="img-fluid border-radius-lg move-on-hover" />
            </a>
          </div>
          <div class="card-body text-center">
            <h4 class="mb-0"></h4>
            <p></p>
            <div class="row justify-content-center text-center"></div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-4">
        <div class="mt-md-0 mt-5">
          <div class="card-header mt-n4 mx-3 p-0 bg-transparent position-relative z-index-2">
            <a class="d-block blur-shadow-image">
              <img src="{% static '/assets/img/parceiros/uan.jpg' %}" alt="img-blur-shadow" class="img-fluid border-radius-lg move-on-hover" />
            </a>
          </div>
          <div class="card-body text-center">
            <h4 class="mb-0"></h4>
            <p></p>
            <div class="row justify-content-center text-center"></div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-4">
        <div class="mt-md-0 mt-5">
          <div class="card-header mt-n4 mx-3 p-0 bg-transparent position-relative z-index-2">
            <a class="d-block blur-shadow-image">
              <img src="{% static '/assets/img/parceiros/ca.jpeg' %}" alt="img-blur-shadow" class="img-fluid border-radius-lg move-on-hover" />
            </a>
          </div>
          <div class="card-body text-center">
            <h4 class="mb-0"></h4>
            <p></p>
            <div class="row justify-content-center text-center"></div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-4">
        <div class="mt-md-0 mt-5">
          <div class="card-header mt-n4 mx-3 p-0 bg-transparent position-relative z-index-2">
            <a class="d-block blur-shadow-image">
              <img src="{% static '/assets/img/parceiros/g1.jpeg' %}" alt="img-blur-shadow" class="img-fluid border-radius-lg move-on-hover" />
            </a>
          </div>
          <div class="card-body text-center">
            <h4 class="mb-0"></h4>
            <p></p>
            <div class="row justify-content-center text-center"></div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-4 col">
        <div class="mt-md-0 mt-5">
          <div class="card-header mt-n4 mx-3 p-0 bg-transparent position-relative">
            <a class="d-block blur-shadow-image">
              <img src="{% static '/assets/img/parceiros/p1.jpg' %}" alt="img-blur-shadow" class="img-fluid border-radius-lg move-on-hover" />
            </a>
          </div>
          <div class="card-body text-center">
            <h4 class="mb-0"></h4>
            <p></p>
            <div class="row justify-content-center text-center"></div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-4">
        <div class="mt-md-0 mt-5">
          <div class="card-header mt-n4 mx-3 p-0 bg-transparent position-relative z-index-2">
            <a class="d-block blur-shadow-image">
              <img src="{% static '/assets/img/parceiros/isia.png' %}" alt="img-blur-shadow" class="img-fluid border-radius-lg move-on-hover" />
            </a>
          </div>
          <div class="card-body text-center">
            <h4 class="mb-0"></h4>
            <p></p>
            <div class="row justify-content-center text-center"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mx-auto text-center">
        <h6 class="text-gradient text-warning"></h6>
        <h2>Patrocinador</h2>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-lg-3 col-6 mb-lg-0 mb-4">
        <div class="card shadow-lg">
          <div class="card-header mt-n4 mx-3 p-0 bg-transparent position-relative z-index-2">
            <a class="d-block blur-shadow-image">
              <img src="{% static '/assets/img/parceiros/marinha.jpg' %}" alt="img-blur-shadow" class="img-fluid border-radius-lg move-on-hover" />
            </a>
          </div>
          <div class="card-body text-center bg-white border-radius-lg p-3 pt-0">
            <h5 class="mt-3 mb-1 d-md-block d-none">Academia Naval</h5>
            <p class="mb-1 d-md-none d-block text-sm font-weight-bold text-darker">Academia Naval</p>
          </div>
        </div>
      </div>
    </div>

    <div class="row mt-5">
      <div class="col-lg-6">
        <h2>Faça parte.</h2>
        <p>Torna-se um parceiro ou patrocinador do maior repositório...</p>
      </div>
      <div class="col-lg-6 text-end d-flex flex-column justify-content-center">
        <button type="button" class="btn bg-gradient-warning mb-0 ms-lg-auto me-lg-0 me-auto mt-lg-0 mt-2">Join Team</button>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/pagina/resultado_pesquisa.html
{% extends 'base_pagina.html' %}{% block corpo %}{% load static %}
<header>
  <div class="page-header min-height-400" style="background-image: url('static/assets/img/banners/b1.jpg')" loading="lazy">
    <span class="mask bg-gradient-dark opacity-8"></span>
  </div>
  <div class="card card-body shadow-blur mx-3 mx-md-4 mt-n10 mb-n3">
    <div class="container">
      <form class="" action="{% url 'pagina:resultado_pesquisa'%}" method="post">
        <div class="row border-radius-md pb-4 p-3 mx-sm-0 mx-1 position-relative">
          {% csrf_token %} {% autoescape on %}
          <div class="col-lg-3 mt-lg-n2 mt-2">
            index
            <label class="ms-0 font-weight-bolder"> <h5>Categoria</h5> </label>
            {{ form.categoria }} {{ form.categoria.errors }}
          </div>
          <div class="col-lg-2 mt-lg-n2 mt-2">
            <label class="ms-0 font-weight-bolder"> <h5>Tipo</h5> </label>
            {{ form.tipo }} {{ form.tipo.errors }}
          </div>
          <div class="col-lg-3 mt-lg-n2 mt-2">
            <label>&nbsp;</label>
            <button type="submit" class="btn bg-gradient-info w-100 mb-0">Pesquisar</button>
          </div>
          {% endautoescape %}
        </div>
      </form>
    </div>
  </div>
</header>

<section class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 mx-auto text-center">
        <!--<h2 class="text-gradient text-primary mb-3">+ 129 de pesquisa</h2>-->
      </div>
    </div>
    <div class="row mt-2">
      {% for dados in lista %}
      <div class="col-lg-10 col-md-8">
        <div class="card card-plain">
          <div class="card-body">
            <div class="author">
              <div class="name">
                <h6 class="mb-0 font-weight-bolder"><a href=""> {{ dados.categoria }}, {{ dados.titulo }}</a></h6>
                <div class="stats"><i class="far fa-clock"></i> {{ dados.ano }}</div>
              </div>
            </div>
            <p class="mt-2">{{ dados.resumo|truncatewords:45 }}</p>
            <a href="{% url 'pagina:visualizar' dados.id %}" class="text-primary icon-move-right">
              Saiba Mais
              <i class="fas fa-arrow-right text-sm ms-1"></i>
            </a>
            <div class="rating mt-2">
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <hr class="horizontal dark my-5" />
  </div>
</section>

{% endblock %}

templates/pagina/visualizar.html
{% extends 'base_pagina.html' %}{% block corpo %}{% load static %}
<header>
  <div class="page-header min-height-400" style="background-image: url('static/assets/img/banners/b1.jpg')" loading="lazy">
    <span class="mask bg-gradient-dark opacity-8"></span>
  </div>
</header>

{% endblock %}