academy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('pagina/', include('pagina.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name="index"),
    path('servicos', views.service, name="servicos"),
    path('login', views.loginUser, name="login"),
    path('about_us', views.about_us, name="about-us"),
    path('pesquisar', views.pesquisar, name="pesquisar"),
    path('home', views.home, name="home"),
    path('registar_arquivos', views.registar_arquivos, name="registar-arquivos"),
    path('listar_arquivos', views.listar_arquivos, name="listar-arquivos"),
   
   
]

templates/baseApp.html
<!--
Author: SOFIL WEB
Author URL: 
-->
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    <meta charset="utf-8" />
    <meta name="description" content="repositorio científico angolano" />
    <meta name="keywords" content="angola, educação, monografias, repositório, cientifico" />
    <meta name="author" content="gunza ismael" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="icon" type="image/png" href="{% static '/asset/imges/icons.png' %}" />
    <title>REPOSITÓRIO INTEGRADO CIÉNTIFICO & ACADÉMICO DE ANGOLA</title>
    <link rel="stylesheet" href="{% static '/asset/css/style-starter.css' %}" />
    <link href="//fonts.googleapis.com/css?family=Hind:400,500,600,700&display=swap" rel="stylesheet" />
  </head>

  <body>
    <!--//top-header-content-->
    <div class="template">
      <header id="site-header" class="fixed-top">
        <div class="container">
          <nav class="navbar navbar-expand-lg navbar-dark stroke">
            <a class="navbar-brand" href="{% url 'app:index' %}">
              <span class="fa fa-lightbulb-o"></span>
              <!--<img src="{% static '/assets/images/icon.png' %}" class="img-fluid"   
                        style="border-radius: 70%; vertical-align: middle; width: 50px;  height: 50px;">-->
              <!--BANTUS-->
              BANTUS
            </a>
            <button
              class="navbar-toggler bg-gradient"
              type="button"
              data-toggle="collapse"
              data-target="#navbarTogglerDemo02"
              aria-controls="navbarTogglerDemo02"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon fa fa-bars"> </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'app:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link effect-3" href="{% url 'app:servicos' %}">Serviços</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link effect-3" href="{% url 'app:index' %}">Parcerias</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link effect-3" href="{% url 'app:about-us' %}">Sobre Nós</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link effect-3" href="{% url 'app:login' %}"><b>Login</b></a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </header>
    </div>
    <!--//top-header-content-->
    {% block corpo %} {% endblock %}

    <!-- //content-6-section -->

    <section class="w3l-download-main">
		<!--/download-->
		<div class="download-content text-center py-5">
			<div class="container py-lg-3">
				<h3 data-aos="fade-up">Repositório Académico<span> Anglano</span>.<br> Divulga aqui!</h3>
				<!--<h6 data-aos="fade-up">Click to Download Usance Application</h6>-->
				<div class="banner-button" data-aos="fade-up">
					<a href="#" class="btn">Regista-se</a><small></small>
				</div>
			</div>
		</div>
		</div>
		<!--//download-->
	</section>
    <!-- footer -->
    <footer class="w3l-footer-16">
      <div class="footer-content py-lg-5 py-4 text-center">
        <div class="container">
          <div class="copy-right">
            <h6><span class="fa fa-heart" aria-hidden="true"></span> love Designed by <a href="#">SOFIL WEB</a></h6>
            <ul class="footer-gd-16">
              <li>© 2020 <b> Repositório Integrado Científico & Académico de Angola.</b></li>
              <li><a href="#">Support</a></li>
              <li><a href="#">Privacy</a></li>
              <li><a href="#">Terms</a></li>
            </ul>
          </div>
          <button onclick="topFunction()" id="movetop" title="Go to top">
            <span class="fa fa-angle-up"></span>
          </button>
        </div>
      </div>

      <script>
        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () {
          scrollFunction();
        };

        function scrollFunction() {
          if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            document.getElementById("movetop").style.display = "block";
          } else {
            document.getElementById("movetop").style.display = "none";
          }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
          document.body.scrollTop = 0;
          document.documentElement.scrollTop = 0;
        }
      </script>
      <!-- //move top -->
      <script>
        $(function () {
          $(".navbar-toggler").click(function () {
            $("body").toggleClass("noscroll");
          });
        });
      </script>
    </footer>
    <!-- //footer -->
  </body>
</html>

<script src="{% static '/asset/js/jquery-3.3.1.min.js' %}"></script>
<!-- disable body scroll which navbar is in active -->

<!--//-->
<script>
  $(function () {
    $(".navbar-toggler").click(function () {
      $("body").toggleClass("noscroll");
    });
  });
</script>
<!--/MENU-JS-->
<script>
  $(window).on("scroll", function () {
    var scroll = $(window).scrollTop();

    if (scroll >= 80) {
      $("#site-header").addClass("nav-fixed");
    } else {
      $("#site-header").removeClass("nav-fixed");
    }
  });

  //Main navigation Active Class Add Remove
  $(".navbar-toggler").on("click", function () {
    $("header").toggleClass("active");
  });
  $(document).on("ready", function () {
    if ($(window).width() > 991) {
      $("header").removeClass("active");
    }
    $(window).on("resize", function () {
      if ($(window).width() > 991) {
        $("header").removeClass("active");
      }
    });
  });
</script>
<!--//MENU-JS-->
<!-- /aos -->
<script src="{% static '/asset/js/aos.js' %}"></script>
<script src="{% static '/asset/js/aosindex.js' %}"></script>
<!-- //aos -->

<script src="{% static '/asset/js/bootstrap.min.js' %}"></script>

templates/home_base.html
<!DOCTYPE html>
{% load static %}
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>BANTUS</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--<link rel="icon" href="{% static '/img/logo.png' %}" type="image/x-icon" />-->

    <link rel="stylesheet" href="{% static '/plugins/bootstrap/dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/fontawesome-free/css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/icon-kit/dist/css/iconkit.min.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/ionicons/dist/css/ionicons.min.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/perfect-scrollbar/css/perfect-scrollbar.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" />
    <!--<link rel="stylesheet" href="{% static '/plugins/tempusdominus-bootstrap-4/build/css/tempusdominus-bootstrap-4.min.css' %}" />-->
    <link rel="stylesheet" href="{% static '/plugins/weather-icons/css/weather-icons.min.css' %}" />
    <!--<link rel="stylesheet" href="{% static '/plugins/c3/c3.min.css' %}" />-->
    <link rel="stylesheet" href="{% static '/dist/css/sweetalert2.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/owl.carousel/dist/assets/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static '/plugins/owl.carousel/dist/assets/owl.theme.default.min.css' %}" />
    <link rel="stylesheet" href="{% static '/dist/css/theme.min.css' %}" />
    <link rel="stylesheet" href="{% static '/dist/css/wizard.css' %}" />
    <link rel="stylesheet" href="{% static '/dist/css/custum.css' %}" />
    <script src="{% static '/src/js/vendor/modernizr-2.8.3.min.js' %}"></script>
  </head>

  <body>
    <!--[if lt IE 8]>
      <p class="browserupgrade">
        You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.
      </p>
    <![endif]-->

    <div class="wrapper">
      <header class="header-top" header-theme="light">
        <div class="container-fluid">
          <div class="d-flex justify-content-between">
            <div class="top-menu d-flex align-items-center">
              <button type="button" class="btn-icon mobile-nav-toggle d-lg-none"><span></span></button>
              <div class="header-search">
                <div class="input-group">
                  <span class="input-group-addon search-close"><i class="ik ik-x"></i></span>
                  <input type="text" class="form-control" />
                  <span class="input-group-addon search-btn"><i class="ik ik-search"></i></span>
                </div>
              </div>
              <button type="button" id="navbar-fullscreen" class="nav-link"><i class="ik ik-maximize"></i></button>
            </div>
            <div class="top-menu d-flex align-items-center">
              <div class="dropdown">
                <a class="dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                  ><img class="avatar" src="{% static 'img/logo.png' %}" alt=""
                /></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                  <a class="dropdown-item" href="#"><i class="ik ik-user dropdown-icon"></i> Profile</a>
                  <a class="dropdown-item" href="#"><i class="ik ik-power dropdown-icon"></i> Logout</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>

      <div class="page-wrap">
        <div class="app-sidebar colored">
          <div class="sidebar-header">
            <a class="header-brand" href="{% url 'app:home' %}">
              <div class="logo-img">
                <!-- <img src="src/img/brand-white.svg" class="header-brand-img" alt="lavalite" />-->
              </div>
              <span class="text">IMBODEIRO<br />Repositório </span>
            </a>
            <button type="button" class="nav-toggle"><i data-toggle="expanded" class="ik ik-toggle-right toggle-icon"></i></button>
            <button id="sidebarClose" class="nav-close"><i class="ik ik-x"></i></button>
          </div>

          <div class="sidebar-content">
            <div class="nav-container">
              <nav id="main-menu-navigation" class="navigation-main">
                <div class="nav-item active">
                  <a href="#"><i class="ik ik-bar-chart-2"></i><span>MENU</span></a>
                </div>

                <div class="nav-lavel">INSTITUIÇÕES</div>
                <div class="nav-item has-sub">
                  <a href="#"><i class="ik ik-book-open"></i><span></span></a>
                  <div class="submenu-content">
                    <a href="" class="menu-item">Adicionar nova instituição</a>
                    <a href="" class="menu-item">Listar instituição</a>
                  </div>
                </div>

                <div class="nav-lavel">ARQUIVOS</div>
                <div class="nav-item has-sub">
                  <a href="#"><i class="ik ik-folder-minus"></i><span></span></a>
                  <div class="submenu-content">
                    <a href="{% url 'app:registar-arquivos' %}" class="menu-item">Adicionar Novo Arquivo</a>
                    <a href="{% url 'app:listar-arquivos' %}" class="menu-item">Listar Arquivos</a>
                    <a href="pages/ui/buttons.html" class="menu-item">Consultar Arquivos</a>
                  </div>
                </div>

                <div class="nav-lavel">UTILIZADOR</div>
                <div class="nav-item has-sub">
                  <a href="#"><i class="ik ik-users"></i><span></span> </a>
                  <div class="submenu-content">
                    <a href="#" class="menu-item active">Criar Conta</a>
                  </div>
                </div>

                <div class="nav-lavel">CONFIGURAÇÃO</div>

                <div class="nav-item has-sub">
                  <a href="#"><i class="ik ik-settings"></i><span></span></a>
                  <div class="submenu-content">
                    <a href="pages/login.html" class="menu-item">Login</a>
                    <a href="pages/register.html" class="menu-item">Register</a>
                    <a href="pages/forgot-password.html" class="menu-item">Forgot Password</a>
                  </div>
                </div>
              </nav>
            </div>
          </div>
        </div>
        <div class="main-content">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                <!--<div id="visitfromworld" style="width: 100%; height: 350px"></div>-->
                {% block corpo %} centro {% endblock %}
              </div>
            </div>
          </div>
        </div>

        <footer class="footer">
          <div class="w-100 clearfix">
            <span class="text-center text-sm-left d-md-inline-block">© 2020 Repositório Integrado Científico & Académico de Angola</span>
            <!--<span class="float-none float-sm-right mt-1 mt-sm-0 text-center">School <i class="fa fa-heart text-danger"></i> <a href="#" class="text-dark" target="_blank">Life</a></span
            >-->
          </div>
        </footer>
      </div>
    </div>

    <script src="{% static '/src/js/vendor/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/plugins/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static '/plugins/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/dist/js/webcam.js' %}"></script>
    <script src="{% static '/dist/js/html2pdf.bundle.min.js' %}"></script>

    <script src="{% static '/plugins/perfect-scrollbar/dist/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static '/plugins/screenfull/dist/screenfull.js' %}"></script>
    <script src="{% static '/plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static '/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static '/plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static '/plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static '/plugins/moment/moment.js' %}"></script>
    <script src="{% static '/plugins/summernote/dist/summernote-bs4.min.js' %}"></script>
    <!--<script src="{% static '/plugins/d3/dist/d3.min.js' %}"></script>
    <script src="{% static '/plugins/c3/c3.min.js' %}"></script>-->
    <script src="{% static '/dist/js/tables.js' %}"></script>
    <!--<script src="{% static 'dist/js/widgets.js' %}"></script>-->
    <script src="{% static '/dist/js/sweetalert2.js' %}"></script>
    <script src="{% static '/dist/js/wizerd.js' %}"></script>
    <script src="{% static '/dist/js/theme.min.js' %}"></script>
    <script src="{% static '/dist/js/help/foto.js' %}"></script>
    <script src="{% static '/dist/js/help/request.js' %}"></script>
    <script language="JavaScript">
      // Configure a few settings and attach camera
      function configure() {
        Webcam.set({
          width: 240,
          height: 240,
          image_format: "jpeg",
          jpeg_quality: 90,
        });
        Webcam.attach("#my_camera");
      }
    </script>
    {% load sweetify %} {% sweetify %}
  </body>
</html>